#!/usr/bin/perl

#
# Copyright (C) 2017 Nethesis S.r.l.
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# nethserver-evebox-update event
#

my $event = 'nethserver-evebox-update';

event_actions($event, qw(
    initialize-default-databases 00
    nethserver-evebox-conf       30
));

event_templates($event, qw(
    /etc/evebox/evebox.yaml
    /etc/sysconfig/evebox
    /etc/httpd/admin-conf.d/evebox.conf
));

event_services($event, 
   'evebox' => 'restart',
   'httpd-admin' => 'reload'
);

#
# nethserver-suricata-save event
#

$event = 'nethserver-suricata-save';

event_services($event,
   'evebox' => 'restart',
);

#
# post-restore-data event
#

$event = 'post-restore-data';

event_actions($event, 
   'nethserver-evebox-fix-rsync-perms' => '10',
);

event_services($event,
   'evebox' => 'restart',
);
