#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Download GeoIP db for EveBox

db=/usr/share/GeoIP/GeoLite2-City.mmdb
rm -f /tmp/GeoLite2-City.mmdb.gz >/dev/null 2>&1

curl -sL http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz -o /tmp/GeoLite2-City.mmdb.gz

gunzip -N /tmp/GeoLite2-City.mmdb.gz
if [ $? -eq 0 ]; then
   mv -f /tmp/GeoLite2-City.mmdb  $db
fi
