#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

bookmark=/var/log/suricata/eve.json.bookmark
log=/var/log/suricata/eve.json

# Prepare json log, otherwise EveBox will fail
if [ ! -f $log ]; then
   touch $log
    chown suricata:suricata $log
fi

# Create bookmark file
if [ ! -f $bookmark ]; then
    touch $bookmark
    chown suricata $bookmark
fi

# Download GeoIP database if doesn't exists
if [ ! -f /usr/share/GeoIP/GeoLite2-City.mmdb ]; then
    /etc/cron.weekly/evebox-geoip
fi

# Make sure working directory has correct permissions
chown suricata:suricata /var/lib/evebox/
